version: '3.8'

services:
  server:
    image: todo-backend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379 #NOTE: redis is now from image redis, not localhost
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database #mongo is from mongo image, defined in this file, not localhost
    container_name: todo-backend-dev # This will name the container hello-front-dev
  redis:
    image: redis
    ports: 
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./redis_data:/data

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
      MONGO_URL: mongodb://the_username:the_password@localhost:3456/the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
volumes:
  mongo_data:
  redis_data: