services:
  app:
    image: phonebook-front-dev
    build:
      context: ./frontend # build in todo-frontend
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: phonebook-front-dev # This will name the container hello-front-dev
    environment:
      #- REACT_BACKEND_URL=http://localhost:8080/api/persons
      - WDS_SOCKET_PORT=0 #enables hot reload
      - WATCHPACK_POLLING=true #enables hot reload
    ports:
      - 3000:3000
    depends_on:
      - server
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro #read only
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
  server:
    image: phonebook-backend-dev
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
   # environment:
     # - REDIS_URL=redis://redis:6379 #NOTE: redis is now from image redis, not localhost
    #  - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database #mongo is from mongo image, defined in this file, not localhost
    container_name: phonebook-backend-dev # This will name the container hello-front-dev
    ports:
      - 3001:3001